### ISSUE TITLE
Segment tunnel configuration description

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-mpls-yang/te#22] opened 2018-02-24 12:05 UTC
In the view to improve the general draft description, it is not trivial to deduce form Yang model how can be manage the case in which Tunnel is not initiated and terminated in the same domain. Typical case could be an E2E  WDM tunnel between two routers crossing Optical Transport network in which optical transponders belongs to routers equipment .

**Comment by ietf-mpls-yang** [comment] 2018-03-01 15:47
This will be clarified in the tutorial draft.

**Comment by ietf-mpls-yang** [comment] 2018-05-11 15:35
Tunnel segment vs. Path segment
Tunnel-1
  src-tp = BN1
  dst-tp = NULL
  primary-path-1
    path-scope = e2e
    start: -
    stop: BN2-BN3-link
  secondary-path-2
    path-scope = e2e
    start = -
    stop = BN2-BN3-link
 secondary-path-3
    path-scope = segment
    start: BN1-AN11-link (incoming)
    stop: AN12-BN2-link

**Comment by italobusi** [comment] 2018-05-18 13:08
This is still not sufficient to cover all the possible cases:

[path-scope-question-01.pptx](https://github.com/ietf-mpls-yang/te/files/2016952/path-scope-question-01.pptx)

**Comment by italobusi** [comment] 2018-05-18 13:15
I think the issue is caused by the fact that there could be up to 4 cases (end-to-end, head segment, intermediate segment and tail segment) and, in some cases, there are not enough information to infer the four cases

These are the possible options:
1) end-to-end Tunnel
    1) end-to-end Path
    2) head segment Path
    3) intermediate segment Path
    4) tail segment Path
2) head segment Tunnel
   1) head segment Path
   2) intermediate segment Path
3) intermediate segment Tunnel
    1) intermediate segment Tunnel
4) tail segment Tunnel
   1) intermediate segment Tunnel
   2) tail segment Tunnel

For tunnel scope, there are two pieces of information (source and destination TTPs) which can be present or not independently: there are four possible cases and this is sufficient to infer the tunnel scope with no need for an explicit indication.

In case of an intermediate segment Tunnel scope, there is no need to encode the path scope.

In  case of head/tail segment Tunnel scope, there are two options so the solution discussed last week provides a binary information which could be used to infer which is the case.

In the case of e2e Tunnel scope, there are four possible options and not sufficient information to infer which is the case

**Comment by ietf-mpls-yang** [comment] 2018-05-25 14:39
address is currently te-tp-id. can generalize unnumbered to cover both numbered and unnumbered

    |  |     |  |     +--:(hop)
     |  |     |  |     |  +--rw hop
     |  |     |  |     |     +--rw node-id?      te-types:te-node-id
     |  |     |  |     |     +--rw link-tp-id?   te-types:te-tp-id
     |  |     |  |     |     +--rw hop-type?     te-hop-type
     |  |     |  |     |     +--rw direction?    te-link-direction

**Comment by ietf-mpls-yang** [comment] 2018-05-25 14:47
AI (Italo/Igor): to follow-up
1) start and end specify the path unambiguously
2) do we need path scope?
3) do we need to specify protection?

**Comment by ietf-mpls-yang** [comment] 2018-05-25 14:48
AI (Tarek): to address the explicit-route

**Comment by ietf-mpls-yang** [comment] 2018-06-01 06:29
Addressed in latest commit for num/unnum hop in explicit route

**Closed by ietf-mpls-yang** 2018-06-01 06:29 UTC
